services:
  - type: web
    name: kfm-delice
    runtime: node
    plan: free
    branch: main
    buildCommand: bun install && bun run build
    startCommand: NODE_ENV=production bun .next/standalone/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
