-- AlterTable: Add missing settings columns to Restaurant
ALTER TABLE "Restaurant" ADD COLUMN IF NOT EXISTS "logo" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Restaurant" ADD COLUMN IF NOT EXISTS "primaryColor" TEXT NOT NULL DEFAULT '#ea580c';
ALTER TABLE "Restaurant" ADD COLUMN IF NOT EXISTS "secondaryColor" TEXT NOT NULL DEFAULT '#dc2626';
ALTER TABLE "Restaurant" ADD COLUMN IF NOT EXISTS "taxRate" DOUBLE PRECISION NOT NULL DEFAULT 15.0;
ALTER TABLE "Restaurant" ADD COLUMN IF NOT EXISTS "currency" TEXT NOT NULL DEFAULT 'GNF';
ALTER TABLE "Restaurant" ADD COLUMN IF NOT EXISTS "facebook" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Restaurant" ADD COLUMN IF NOT EXISTS "instagram" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Restaurant" ADD COLUMN IF NOT EXISTS "twitter" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Restaurant" ADD COLUMN IF NOT EXISTS "latitude" DOUBLE PRECISION NOT NULL DEFAULT 9.5092;
ALTER TABLE "Restaurant" ADD COLUMN IF NOT EXISTS "longitude" DOUBLE PRECISION NOT NULL DEFAULT -13.7122;
